all:
	gcc -o clustershell_client clustershell_client.c -Wall -Wextra -pthread
	gcc -o clustershell_server clustershell_server.c -Wall -Wextra -pthread
clean:
	rm clustershell_client clustershell_server
